# Generated by Django 2.1.7 on 2022-05-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='movies/')),
                ('category', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Biography', 'Biography'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('Film-Noir', 'Film-Noir'), ('History', 'History'), ('Horror', 'Horror'), ('Music', 'Music'), ('Musical', 'Musical'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Sport', 'Sport'), ('Thriller', 'Thriller'), ('War', 'War')], max_length=255)),
                ('language', models.CharField(choices=[('Nepali', 'Nepali'), ('English', 'English'), ('Newari', 'Newari'), ('Bhojpuri', 'Bhojpuri'), ('Limbu', 'Limbu'), ('Tamang', 'Tamang'), ('Gurung', 'Gurung'), ('Rai', 'Rai')], max_length=255)),
                ('status', models.CharField(choices=[('RA', 'Recently Added'), ('MW', 'Most Watched'), ('TR', 'Top Rated'), ('FA', 'Featured')], max_length=255)),
                ('duration', models.IntegerField()),
                ('year_of_production', models.DateField()),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
