# Generated by Django 2.1.7 on 2022-05-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20220513_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='movie.Genre'),
        ),
    ]
